import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import axios from 'axios';
import { RootState, AppThunk } from './store';
// import { fetchCount } from '../features/counter/counterAPI';

export interface TypingState {
  status: 'idle' | 'loading' | 'failed' | 'succeed';
  textGenerator : Array<string>;
  error:string|undefined;
  matchTextNum:number;
  isTrueText:Array<boolean>;
  situation:'idle'|'started'|'finished';
  typedText:string;
}

const initialState: TypingState = {
  status: 'idle',
  textGenerator:[],
  error:"",
  matchTextNum:0,
  isTrueText:[],
  situation:'idle',
  typedText:'',
};


export const getText = createAsyncThunk(
  'typing/getText',
  async() => {
    const res = axios.get(`https://baconipsum.com/api/?type=all-meat`).then(response => response.data);
    return res;
  }
)

export const TypingSlice = createSlice({
  name: 'typing',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    incrementTextNum:(state)=>{
      state.matchTextNum += 1;
    },
    addbool:(state,action)=>{
      state.isTrueText.push(action.payload);
    },
    reset : (state) => {
      state.situation = 'idle';
      state.matchTextNum = 0;
      state.isTrueText = [];
      state.typedText = "";
    },
    changeSituation:(state,action) => {
      state.situation = action.payload;
    },
    typeText:(state,action) => {
      state.typedText = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
        .addCase(getText.pending,(state)=> {
          state.status = 'loading';
        })
        .addCase(getText.fulfilled,(state,action)=> {
          state.status = "succeed";
          state.textGenerator = action.payload[0].split(" ").filter((text:string)=>text!=="");
        })
        .addCase(getText.rejected,(state,action)=> {
          state.status = 'failed';
          state.error = action.error.message;
        })
  },
});

export const { incrementTextNum,addbool,reset,changeSituation,typeText} = TypingSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectTextGenerator = (state: RootState) => state.typing.textGenerator;
export const selectMatchTextNum = (state:RootState) => state.typing.matchTextNum;
export const selectIsTrueText = (state: RootState) => state.typing.isTrueText;
export const selectSituation = (state:RootState) => state.typing.situation;
export const selectTypedText = (state:RootState) => state.typing.typedText;


// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default TypingSlice.reducer;
